[package]
name = "rpn-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"

[[bin]]
name = "rpn"
path = "src/bin/rpn.rs"

[[bin]]
name = "infix"
path = "src/bin/infix.rs"
